version: '3.6'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    expose:
      - 5432
    volumes:
      - ./init_model_db.sql:/docker-entrypoint-initdb.d/init_model_db.sql
      - model_data:/var/lib/postgresql/data/
  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
        #PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 30 
        PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
        PGADMIN_DEFAULT_PASSWORD: "admin123!"
    depends_on:
        - postgres
    ports: 
        - "5050:80"   
  webserver:
    build: ./airflow
    #image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://airflow:airflow@postgres:5432/model_db # set uri to get conn in dag (workaround)
      - MODEL_DATABASE_CONN_NAME=postgres_hook
      
      - AIRFLOW__CORE__FERNET_KEY= 'qjpPmZDrA0fzAKTyuVTmX9ISvpPRFbS2K4Mq1Zwtjzk='
      #- AIRFLOW__CONN__POSTGRES_HOOK=postgres://airflow:airflow@postgres:5432/model_db #create db conn
      - LOAD_EX=n
      - EXECUTOR=Local
    #volumes: # just for testing purposes...
      #- ./datasets/:/usr/local/ 
      #- ./models:/usr/local/model/
      #- ./airflow/dags:/usr/local/airflow/dags
      # copy files
      #- /production/model/
    ports:
      - "8080:8080"
    command: webserver 
    #command: sh -c "webserver && export PYTHONPATH=/usr/local/models:$$PYTHONPATH"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 2
    
# attach persistant docker volume    
volumes:
  model_data: